- README.md
- application/modules/assets/views/scripts/index/entertime.phtml
- application/modules/assets/views/scripts/index/week.phtml
- application/modules/expenses/controllers/ReceiptsController.php
- application/modules/timemanagement/controllers/EmptimesheetsController.php
- application/modules/timemanagement/controllers/ReportsController.php
- application/modules/timemanagement/views/scripts/emptimesheets/displayweeks.ajax.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/empdisplayweeks.ajax.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/employeetimesheet.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/emptimesheetmonthly.ajax.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/emptimesheetweekly.ajax.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/index.phtml
- application/modules/timemanagement/views/scripts/index/entertime.phtml
- application/modules/timemanagement/views/scripts/index/index.phtml
- application/modules/timemanagement/views/scripts/index/week.phtml
> Allow future timesheets

- application/modules/default/views/scripts/organisationinfo/index.phtml
- patches/patches_1.1.5/application/modules/default/views/scripts/organisationinfo/index.phtml
- patches/patches_2.0/application/modules/default/views/scripts/organisationinfo/index.phtml
> Google Maps API key

- application/modules/default/forms/Dependencydetails.php
- application/modules/default/forms/Educationdetails.php
- application/modules/default/forms/Myteamemployee.php
- application/modules/default/forms/Roles.php
- application/modules/default/forms/departmentsreport.php
- application/modules/default/forms/employee.php
- application/modules/default/forms/empsalarydetails.php
- application/modules/default/forms/empscreeningreport.php
- application/modules/default/forms/holidaygroups.php
- application/modules/default/forms/viewprofile.php
- public/media/js/pa.js
Allow special characters in names
> Custom personal data

- application/modules/default/plugins/AccessControl.php
Removed access to experience details (now labeled subcontractor) from
team leads and employees.
> Change experience details permissions

- application/modules/default/plugins/AccessControl.php
Remove access for several personal detail tabs for employees and team
leads
> Access control

- Zend/View/Helper/Employeedetails.php
Disable showing several tabs in employee details views
> Disable menu items in employee tabs

- application/modules/timemanagement/views/scripts/projects/edit.phtml
- application/modules/timemanagement/views/scripts/reports/index.phtml
- application/modules/timemanagement/views/scripts/reports/tmreport.phtml
Greater year range available on month picker
> Available years

- application/modules/assets/views/scripts/index/entertime.phtml
- application/modules/assets/views/scripts/index/week.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/employeetimesheet.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/emptimesheetmonthly.ajax.phtml
- application/modules/timemanagement/views/scripts/emptimesheets/index.phtml
- application/modules/timemanagement/views/scripts/index/entertime.phtml
- application/modules/timemanagement/views/scripts/index/index.phtml
- application/modules/timemanagement/views/scripts/index/week.phtml
Added one year to final selectable year, to allow selection of the
following year
> Month picker

- application/modules/default/models/Employee.php
Include management in service request executor list
> Service request executors

- application/modules/default/models/Employee.php
Allow service request executor to be from any business unit or
department
> Service request executor business unit / department

- README.md
- application/modules/default/library/sapp/Mail.php
- install/step4.php
- success.php
Remove instances where superadmin email address was used
> Always send email from donotreply address

- application/modules/timemanagement/controllers/EmptimesheetsController.php
Always show all weeks on the week picker in week views
> Never hide weeks

- application/modules/timemanagement/controllers/EmptimesheetsController.php
Reverts go-faustino/sentrifugo#33
> Revert "Never hide weeks"

- application/modules/default/models/Users.php
Allow reporting manager to be from any department within the company
> Remove department id from reporting manager query

- application/modules/default/forms/Myteamemployee.php
- application/modules/default/forms/employee.php
jobtitle (career track) and position (career level) employee fields are
mandatory
> job title and position as mandatory fields

- application/modules/default/forms/Myteamemployee.php
- application/modules/default/forms/employee.php
jobtitle (career track) and position (career level) as mandatory fields
> Mandatory employee fields

- application/modules/default/views/scripts/employee/add.phtml
- application/modules/default/views/scripts/employee/edit.phtml
- application/modules/default/views/scripts/myemployees/add.phtml
- application/modules/default/views/scripts/myemployees/edit.phtml
Signal job title and position (career level and career track) as
mandatory (red asterisk) on forms
> Mark jobtitle and position fields as mandatory on form

- public/application_constants.php
Includes install date variable with minimum date value
> Declare install date variable

- application/layouts/scripts/timemanagementheader.phtml
- application/modules/timemanagement/controllers/NotificationsController.php
Employee timesheet submission notifications only start after saved
install date
> Notifications begin on install date

- application/modules/default/controllers/IndexController.php
- application/modules/default/controllers/OncallrequestController.php
- application/modules/default/views/scripts/oncallrequest/calenderview.phtml
- application/modules/default/views/scripts/oncallrequest/index.phtml
- application/modules/services/models/Oncalls.php
- public/media/js/hrms.js
- public/media/timemanagement/js/timemanagement.js
enable weekends for on call request date picker
> On call calendar - datepicker

- application/modules/default/models/Oncallrequest.php
Fixed a bug, where the manager employee on call grid was calling manager employee vacations
> On call calendar

- application/modules/default/controllers/LeaverequestController.php
- application/modules/default/controllers/OncallrequestController.php
- application/modules/default/views/scripts/oncallrequest/index.phtml
- application/modules/services/models/Leaves.php
- application/modules/services/models/Oncalls.php
requested separately:
- correct message
> Same month leave on call

- application/modules/default/controllers/LeaverequestController.php
- application/modules/default/forms/leaverequest.php
- application/modules/services/models/Leaves.php
Allow requesting half day leaves for multiple days
> Half day leave for multiple days

- README.md
- application/modules/timemanagement/controllers/CronjobController.php
- application/modules/timemanagement/models/Users.php
Remove employees in 'deputation' status from emails
> Timesheet cronjob

- application/modules/default/controllers/ReportsController.php
- application/modules/default/models/Employee.php
> last training / certification details on employee

- application/modules/timemanagement/controllers/EmptimesheetsController.php
Missed calWeek initialization first time around
> remove double slashes

- .gitignore
- application/modules/timemanagement/controllers/IndexController.php
- application/modules/timemanagement/models/Projects.php
- application/modules/timemanagement/models/Users.php
Additional calendar week calculations corrections
> Calendar week bug

- .gitignore
- composer.json
- composer.lock
- index.php
This stops random whitescreens and provides useful debugging. Requires 'composer install' to be run prior to installing, so you may want to not accept this, or, add everything in vendor to git (which is added to .gitignore).
> Add Whoops handler for better errors
